# Generated by Django 3.1.7 on 2021-03-19 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('department', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incident_location', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('cause', models.TextField()),
                ('action_taken', models.TextField()),
                ('sub_incident', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidentdb',
                'ordering': ['date', 'time'],
            },
        ),
    ]
